// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef splash_h
#define splash_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *splash_wnd;
#include <FL/Fl_Box.H>
extern Fl_Box *header_box;
extern Fl_Box *footer_box;
Fl_Double_Window* make_window();
#endif
